version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./docker/nginx/dev/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/dev/ssl:/etc/letsencrypt
      - ./docker/nginx/dev/ssl-data:/var/lib/letsencrypt
      - ./:/var/www/html
      - ./docker/nginx/dev/logs/nginx:/var/log/nginx
      - ./docker/socket:/socket
    container_name: wall_nginx_dev
    depends_on:
      - app
    networks:
      - web
    restart: always

  app:
    build:
      context: ./docker/app/dev
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/socket:/socket
    container_name: wall_app_dev
    depends_on:
      - db
    networks:
      - web
    restart: always

  scheduler:
    build:
      context: ./docker/app/dev
      dockerfile: Dockerfile
    command: /bin/sh -c "while :; do php /var/www/html/artisan schedule:run; sleep 60; done"
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - web

  db:
    image: library/mariadb:11.4
    volumes:
      - wall_dev_db_data_dev:/var/lib/mysql
    environment:
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    ports:
      - "3307:3306"
    container_name: wall_db_dev
    networks:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/nginx/dev/ssl:/etc/letsencrypt
      - ./docker/nginx/dev/ssl-data:/var/lib/letsencrypt
      - ./:/var/www/html
    networks:
      - web
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done'"

volumes:
  wall_db_data_dev:
    driver: local

networks:
  web:
    driver: bridge
