version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./docker/nginx/prod/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/prod/ssl:/etc/letsencrypt
      - ./docker/nginx/prod/ssl-data:/var/lib/letsencrypt
      - ./:/var/www/html
      - ./docker/nginx/prod/logs/nginx:/var/log/nginx
      - ./docker/socket:/socket
    container_name: wall_nginx_prod
    depends_on:
      - app
    networks:
      - web_prod
    restart: always

  app:
    build:
      context: ./docker/app/prod
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/socket:/socket
    container_name: wall_app_prod
    depends_on:
      - db
    networks:
      - web_prod
    restart: always

  scheduler:
    build:
      context: ./docker/app/prod
      dockerfile: Dockerfile
    command: /bin/sh -c "while :; do php /var/www/html/artisan schedule:run; sleep 60; done"
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - web_prod

  db:
    image: library/mariadb:11.4
    volumes:
      - wall_db_data_prod:/var/lib/mysql
    environment:
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    ports:
      - "3306:3306"
    container_name: wall_db_prod
    networks:
      - web_prod

  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/nginx/prod/ssl:/etc/letsencrypt
      - ./docker/nginx/prod/ssl-data:/var/lib/letsencrypt
      - ./:/var/www/html
    networks:
      - web_prod
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done'"

volumes:
  wall_db_data_prod:
    driver: local

networks:
  web_prod:
    driver: bridge
