version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/letsencrypt
      - ./docker/nginx/ssl-data:/var/lib/letsencrypt
      - ./:/var/www/html
      - ./docker/nginx/logs/nginx:/var/log/nginx
      - ./docker/socket:/socket
    container_name: wall_nginx
    depends_on:
      - app
    networks:
      - web
    restart: always

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/socket:/socket
    container_name: wall_app
    depends_on:
      - db
    networks:
      - web
    restart: always

  db:
    image: mariadb:11.4
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_ROOT_HOST=%
      - MARIADB_DATABASE=wall
    ports:
      - "3306:3306"
    container_name: wall_db
    networks:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/nginx/ssl:/etc/letsencrypt
      - ./docker/nginx/ssl-data:/var/lib/letsencrypt
      - ./:/var/www/html
    networks:
      - web
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done'"

networks:
  web:
    driver: bridge
