name: cd

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/rock-n-wall
          git restore .
          git pull
          docker exec wall_app composer install
          docker exec wall_app php artisan migrate:fresh --seed
          docker exec wall_app php artisan l5-swagger:generate
